vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|22 Jun 2012 16:41:17 -0000
vti_extenderversion:SR|5.0.2.6790
vti_title:SR|Calvary Comics: Home Page
vti_lineageid:SR|{60FDA541-F9D1-46C4-9C38-E17F9A05560B}
vti_backlinkinfo:VX|comics/ejpace/page2.html comics/CLENDENNEN/back.html comics/GloryToGod/page7.html comics/Roever/page1.html comics/sadhu/page3.html comics/GloryToGod/page3.html comics/GloryToGod/page5.html comics/sadhu/index.html comics/sadhu/page1.html comics/zulu/page1.html comics/zulu/page3.html comics/GloryToGod/index.html comics/GloryToGod/page1.html comics/MLMC/page2.html comics/MLMC/page4.html comics/zulu/index.html comics/CLENDENNEN/page5.html comics/GloryToGod/poster.html comics/Puddles/page6.html comics/zulu/foreword.html about.html comics/CLENDENNEN/page1.html comics/CLENDENNEN/page3.html comics/Puddles/page2.html comics/Puddles/page4.html links.html reviews/page7.html comics/CLENDENNEN/index.html order/cancel.html reviews/page5.html comics/ejpace/page5.html comics/ejpace/page7.html comics/unshackled/page3.html comics/unshackled/page5.html reviews/page1.html reviews/page3.html comics/ejpace/page1.html comics/ejpace/page3.html comics/Puddles/pageBack.html comics/sadhu/page6.html comics/unshackled/index.html comics/unshackled/page1.html reviews/index.html comics/ejpace/index.html comics/GloryToGod/page6.html comics/GloryToGod/pageBack.html comics/Roever/page2.html comics/sadhu/page4.html comics/zulu/page4.html contact.asp comics/ejpace/poster.html comics/GloryToGod/page2.html comics/GloryToGod/page4.html comics/sadhu/page2.html comics/zulu/page2.html comics/MLMC/page3.html comics/MLMC/page5.html order.html comics/MLMC/index.html comics/MLMC/page1.html comics/Puddles/page5.html comics/Puddles/page7.html comics/Road/index.html comics/zulu/back.html comics/CLENDENNEN/page2.html comics/CLENDENNEN/page4.html comics/ejpace/pageBack.html comics/Puddles/page1.html comics/Puddles/page3.html comics/zulu/forward.html Copy\\ of\\ contact.asp comics/ejpace/page8.html comics/Puddles/index.html reviews/page4.html reviews/page6.html comics/ejpace/page6.html comics/unshackled/page2.html comics/unshackled/page4.html reviews/page2.html comics/ejpace/page4.html comics/Roever/page3.html order/success.html comics/Roever/index.html comics/sadhu/page5.html comics/zulu/page5.html home.html
vti_cacheddtm:TX|22 Jun 2012 16:41:17 -0000
vti_filesize:IR|9041
vti_cachedtitle:SR|Calvary Comics: Home Page
vti_cachedbodystyle:SR|<BODY leftmargin="0" rightmargin="0" bottommargin="0" topmargin="0" marginheight="0" marginwidth="0" class="bgcolor">
vti_cachedlinkinfo:VX|Q|/css/stylesheet.css H|home.html S|img/logo_small.gif S|img/space.gif H|about.html S|img/space.gif S|img/space.gif H|contact.asp S|img/space.gif S|img/space.gif H|reviews/index.html S|img/space.gif S|img/space.gif H|links.html S|img/space.gif S|img/space.gif H|order.html S|img/space.gif S|img/space.gif S|img/space.gif H|mailto:editor@calvarycomics.com
vti_cachedsvcrellinks:VX|FQUS|css/stylesheet.css FHUS|home.html FSUS|img/logo_small.gif FSUS|img/space.gif FHUS|about.html FSUS|img/space.gif FSUS|img/space.gif FHUS|contact.asp FSUS|img/space.gif FSUS|img/space.gif FHUS|reviews/index.html FSUS|img/space.gif FSUS|img/space.gif FHUS|links.html FSUS|img/space.gif FSUS|img/space.gif FHUS|order.html FSUS|img/space.gif FSUS|img/space.gif FSUS|img/space.gif NHUS|mailto:editor@calvarycomics.com
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|description keywords Christian\\ comics,\\ Sadhu\\ Sundar\\ Singh,\\ Alec\\ Stevens,\\ graphic\\ novel,\\ India,\\ Gandhi,\\ Corrie\\ ten\\ Boom vendor Alec\\ Stevens vendor_website www.CalvaryComics.com author Adam\\ Cleveland HTTP-EQUIV=imagetoolbar no
vti_charset:SR|windows-1252
